### ISSUE TITLE
Latest grafana: could not start plugin alexanderzobnin-zabbix-datasource

### ISSUE THREAD

**Issue by SklyarHappens** [alexanderzobnin/grafana-zabbix#1577]
Hello!
Could not start plugin. In grafana web-interface: Plugin unavailable.
problem is like this: https://github.com/alexanderzobnin/grafana-zabbix/issues/1510
Tried with allow_loading_unsigned_plugins in grafana.ini and without it.

**Expected behavior**
plugin works :)

**Log**
```
logger=plugin.signature.validator t=2023-03-01T14:46:52.40691639Z level=warn msg="Permitting unsigned plugin. This is not recommended" pluginID=grafana-piechart-panel
logger=plugin.loader t=2023-03-01T14:46:52.407027348Z level=warn msg="Plugin missing module.js" pluginID=grafana-piechart-panel warning="Missing module.js, If you loaded this plugin from git, make sure to compile it." path=/var/lib/grafana/plugins/grafana-piechart-panel/dist/module.js
logger=plugin.signature.validator t=2023-03-01T14:46:52.407065731Z level=warn msg="Permitting unsigned plugin. This is not recommended" pluginID=goshposh-metaqueries-datasource
logger=plugin.loader t=2023-03-01T14:46:52.407374235Z level=info msg="Plugin registered" pluginID=marcusolsson-json-datasource
logger=plugin.loader t=2023-03-01T14:46:52.407413898Z level=info msg="Plugin registered" pluginID=sbueringer-consul-datasource
logger=plugin.loader t=2023-03-01T14:46:52.423409833Z level=info msg="Plugin registered" pluginID=alexanderzobnin-zabbix-triggers-panel
logger=plugin.loader t=2023-03-01T14:46:52.423451447Z level=info msg="Plugin registered" pluginID=sebastiangunreben-cdf-panel
logger=plugin.loader t=2023-03-01T14:46:52.423459703Z level=info msg="Plugin registered" pluginID=hawkular-datasource
logger=plugin.loader t=2023-03-01T14:46:52.423467082Z level=info msg="Plugin registered" pluginID=alexanderzobnin-zabbix-app
logger=plugin.loader t=2023-03-01T14:46:52.423473751Z level=info msg="Plugin registered" pluginID=yesoreyeram-boomtable-panel
logger=plugin.loader t=2023-03-01T14:46:52.423479938Z level=info msg="Plugin registered" pluginID=simpod-json-datasource
logger=plugin.loader t=2023-03-01T14:46:52.423486815Z level=info msg="Plugin registered" pluginID=camptocamp-prometheus-alertmanager-datasource
logger=plugin.loader t=2023-03-01T14:46:52.423496971Z level=info msg="Plugin registered" pluginID=alexanderzobnin-zabbix-datasource
logger=plugin.loader t=2023-03-01T14:46:52.429578037Z level=error msg="Could not start plugin" pluginId=alexanderzobnin-zabbix-datasource err="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
logger=plugin.loader t=2023-03-01T14:46:52.429678238Z level=info msg="Plugin registered" pluginID=grafana-piechart-panel
```

grafana.ini
```
[analytics]
check_for_updates = true
[auth]
disable_login_form = true
disable_signout_menu = true
[auth.anonymous]
enabled = true
org_role = Admin
[grafana_net]
url = https://grafana.blabla
[log]
mode = console
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource,goshposh-metaqueries-datasource,grafana-piechart-panel
enable_alpha = true
[server]
domain = grafana.blabla
root_url = http://grafana.blabla
[users]
viewers_can_edit = true
```

datasource.yml
```
-name: zbx.blabla
  type: alexanderzobnin-zabbix-datasource
  url: http://zbx.blabla/api_jsonrpc.php 
  access: proxy
  editable: false
  isDefault: false
  jsonData:
    addThresholds: false
    alerting: false
    alertingMinSeverity: 3
    cacheTTL: 1h
    dbConnectionDatasourceName: MySQL Zabbix
    dbConnectionEnable: false
    dbConnectionRetentionPolicy: one_year
    disableDataAlignment: false
    disableReadOnlyUsersAck: false
    password: $ZBX_PASS
    trends: false
    trendsFrom: 7d
    trendsRange: 4d
    useZabbixValueMapping: true
    username: admin
```

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.2.2   | 4.4.5  | 4.1.5                 |
also tried:
| 9.2.2   | 4.4.5  | 4.2.10                |
| 9.4.1   | 4.4.5  | 4.2.10                |

works fine even without allow_loading_unsigned_plugins:
| 8.3.6.   | 4.4.5  | 4.1.5                |
