### ISSUE TITLE
Is having a nested map in the jsonData a good idea ?

### ISSUE THREAD

**Issue by g-goessel** [alexanderzobnin/grafana-zabbix#598]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request

I am referring to this block : [line](https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/datasource-zabbix/datasource.js#L54)
You store the dbConnection details like that :
```yaml
dbConnection:
        enable: true
        datasourceId: 3
```
but this creates a second map inside the jsonData map and it is not supported by Grafana while provisioning.

Don't you think using dbConnectionEnable and dbConetionDatasourceId would be a good idea ?
