### ISSUE TITLE
Direct DB connection datasource fails to load when ds is provisioned

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#711]
Example provisioning config:
```yaml
apiVersion: 1

datasources:
- name: Zabbix Provisioned
  type: alexanderzobnin-zabbix-datasource
  url: http://zabbix.grafana-zabbix.org/api_jsonrpc.php
  access: proxy
  jsonData:
    username: zabbix
    password: zabbix
    dbConnectionEnable: true
    dbConnectionDatasourceName: MySQL Zabbix Provisioned
  orgId: 1
  version: 1
  editable: false

- name: MySQL Zabbix Provisioned
  type: mysql
  url: localhost:3306
  database: zabbix
  user: grafana
  password: password
  orgId: 1
  version: 1
  editable: false
```

Configured SQL datasource doesn't appear and there's an error when you're trying to test datasource:
```
Connection failed: Query missing datasourceId
```

![Screenshot from 2019-03-19 10-43-28](https://user-images.githubusercontent.com/4932851/54588375-dba01600-4a33-11e9-819f-0a0b14c9e1ae.png)
